spring:
  datasource:
    url: jdbc:h2:file:~/h2/coumon;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: jy
    password: 1234
    hikari:
      maximum-pool-size: 1000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
  h2:
    console:
      enabled: true

secret:
  key: "coumon@secret@key@1234"

big-queue.dir: /tmp/bigqueue